oliverklee/ext-feuserextrafields

- .github/workflows/ci.yml
- Tests/Functional/HelloWorldTest.php
- Tests/Unit/HelloWorldTest.php
- composer.json
Also add the corresponding CI jobs.
> [FEATURE] Add dummy unit and functional tests

- Classes/Domain/Model/FrontendUser.php
- Configuration/TCA/Overrides/fe_users.php
- Resources/Private/Language/de.locallang.xlf
- Resources/Private/Language/fr.locallang.xlf
- Resources/Private/Language/locallang.xlf
- Resources/Private/Language/nl.locallang.xlf
- Tests/Functional/Domain/Repository/Fixtures/UserWithAllScalarData.xml
- Tests/Functional/Domain/Repository/FrontendUserRepositoryTest.php
- Tests/Unit/Domain/Model/FrontendUserTest.php
- ext_tables.sql
The only exception is the `static_info_country` field, which
required the `static_info_tables` extension and will be added
in a separate change.
Part of #25
> [FEATURE] Add fields from sr_feuser_register

- Documentation/AddedFields.rst
> [TASK] Document the new fields

- Documentation/ExtbaseModels.rst
> [TASK] Document that the Extbase models have no validation

- README.md
Also fix the URL of the code coverage badge image.
> [TASK] Reorder the badges in the README

- README.md
Also drop the badge for the latest version (as this is not reliable).
> [TASK] Reorder the badges again

- README.md
> [BUGFIX] Fix the link to the code coverage report in the README

- .github/workflows/ci.yml
- .github/workflows/codecoverage.yml
> [TASK] Switch the CI builds to Composer 2.3

- .github/workflows/codecoverage.yml
- .gitignore
- README.md
- composer.json
> [TASK] Switch the code coverage collection to Coveralls

- .gitignore
Just to make sure if someone runs the CI steps locally.
> [TASK] Git-ignore the CI coverage directory

- composer.json
That task is no CI task that is intended to be called from the outside.
> [TASK] Rename the Composer task for creating coverage directories

- CHANGELOG.md
- Resources/Private/Language/de.locallang.xlf
> [BUGFIX] Fix the German label for `static_info_country`

- CHANGELOG.md
- Tests/Functional/Domain/Repository/Fixtures/Pages.xml
- Tests/Functional/Domain/Repository/FrontendUserRepositoryTest.php
- Tests/Functional/Domain/Repository/FrontendUserWithCountryRepositoryTest.php
- Tests/Unit/Domain/Model/FrontendUserTest.php
- composer.json
> [TASK] Add tests concerning handling a user's PID

- composer.json
- phpstan-baseline.neon
- phpstan.neon
> [TASK] Add PHPStan strict rules

- CHANGELOG.md
- Classes/Domain/Repository/DirectPersistInterface.php
- Classes/Domain/Repository/DirectPersistTrait.php
- Classes/Domain/Repository/FrontendUserGroupRepository.php
- Classes/Domain/Repository/FrontendUserRepository.php
- Classes/Domain/Repository/FrontendUserWithCountryRepository.php
- Tests/Functional/Domain/Repository/FrontendUserGroupRepositoryTest.php
- Tests/Functional/Domain/Repository/FrontendUserRepositoryTest.php
- Tests/Functional/Domain/Repository/FrontendUserWithCountryRepositoryTest.php
- Tests/Unit/Domain/Repository/FrontendUserGroupRepositoryTest.php
- Tests/Unit/Domain/Repository/FrontendUserRepositoryTest.php
- Tests/Unit/Domain/Repository/FrontendUserWithCountryRepositoryTest.php
> [FEATURE] Add `Repository.persistAll`

- .github/workflows/ci.yml
- .github/workflows/publish.yml
> [TASK] Update the GitHub runners to the latest Ubuntu LTS version

- CHANGELOG.md
- Classes/Domain/Model/FrontendUser.php
Also make the arrays with the valid enumerations values public
for easy usage from other classes.
Fixes #92
> [CLEANUP] Improve the type annotations for the enumerations

- CHANGELOG.md
- Classes/Domain/Model/FrontendUser.php
- Classes/Domain/Model/FrontendUserGroup.php
- Classes/Domain/Model/FrontendUserWithCountry.php
The maximum lengths match the column definitions in the database.
Fixes #82
> [FEATURE] Add length validation to the model properties

- .github/workflows/ci.yml
- composer.json
- phive.xml
This avoids one part of dependency hell.
Fixes #122
> [TASK] Move PHPCPD to PHIVE

- .github/workflows/ci.yml
- .github/workflows/codecoverage.yml
> [TASK] Switch CI to Composer 2.4

- CHANGELOG.md
- Tests/Functional/Domain/Model/Fixtures/XclassFrontendUser.php
- Tests/Functional/Domain/Model/Fixtures/XclassFrontendUserGroup.php
- Tests/Functional/Domain/Model/Fixtures/XclassFrontendUserWithCountry.php
- Tests/Functional/Domain/Model/FrontendUserGroupTest.php
- Tests/Functional/Domain/Model/FrontendUserTest.php
- Tests/Functional/Domain/Model/FrontendUserWithCountryTest.php
> [FEATURE] Add tests that the models can be XCLASSed

- CHANGELOG.md
- Tests/Unit/Domain/Repository/FrontendUserGroupRepositoryTest.php
- Tests/Unit/Domain/Repository/FrontendUserRepositoryTest.php
- Tests/Unit/Domain/Repository/FrontendUserWithCountryRepositoryTest.php
- Tests/Unit/Fixtures/StubObjectManager.php
- composer.json
- phpstan-baseline.neon
> [TASK] Drop the Prophecy dependency

- composer.json
> [TASK] Add `bnf/phpstan-psr-container` to the PHPStan toolchain

- CHANGELOG.md
- README.md
- composer.json
- ext_emconf.php
> [FEATURE] Allow installation with TYPO3 11LTS

- CHANGELOG.md
- Configuration/Services.yaml
- Tests/Functional/Domain/Repository/FrontendUserGroupRepositoryTest.php
- Tests/Functional/Domain/Repository/FrontendUserRepositoryTest.php
- Tests/Functional/Domain/Repository/FrontendUserWithCountryRepositoryTest.php
> [BUGFIX] Configure and use DI for the repositories in 11LTS

- .github/workflows/ci.yml
- CHANGELOG.md
> [FEATURE] Add TYPO3 11LTS to the build matrix

- .github/workflows/ci.yml
- CHANGELOG.md
- composer.json
- ext_emconf.php
> [FEATURE] Add support for PHP 8.2

- .github/workflows/ci.yml
- .github/workflows/codecoverage.yml
- CHANGELOG.md
Also switch the code coverage collection from TYPO3 10LTS to 11LTS.
Fixes #155
> [TASK] Switch CI quality checks to PHP 8

- CHANGELOG.md
- Configuration/TCA/Overrides/fe_users.php
> [BUGFIX] Stop using the deprecated `TYPO3_MODE` constant

- .phpstorm.meta.php
- composer.json
> [BUGFIX] Also PHP-lint hidden files

- CHANGELOG.md
- Classes/Domain/Repository/FrontendUserGroupRepository.php
- Tests/Functional/Domain/Repository/FrontendUserGroupRepositoryTest.php
> [FEATURE] Add `FrontendUserGroupRepository::findByUids`

- CHANGELOG.md
- Configuration/Services.yaml
This fixes problems with DI on TYPO3 10.
> [BUGFIX] Configure DI for the repositories

- CHANGELOG.md
- composer.json
> [TASK] Require TYPO3 ^11.5.4 for TYPO3 11LTS

- CHANGELOG.md
- Classes/Domain/Model/FrontendUser.php
- Configuration/TCA/Overrides/fe_users.php
- Resources/Private/Language/de.locallang.xlf
- Resources/Private/Language/locallang.xlf
- Tests/Functional/Domain/Repository/Fixtures/UserWithAllScalarData.xml
- Tests/Functional/Domain/Repository/FrontendUserRepositoryTest.php
- Tests/Functional/Domain/Repository/FrontendUserWithCountryRepositoryTest.php
- Tests/Unit/Domain/Model/FrontendUserTest.php
> [FEATURE] Add a gender value "diverse"

- CHANGELOG.md
- Classes/Domain/Model/FrontendUserWithCountry.php
- Classes/Domain/Repository/FrontendUserWithCountryRepository.php
> [TASK] Deprecate `FrontendUserWithCountry` and its repository

- README.md
> [BUGFIX] Switch the license badge in the README to shields.io

- .github/workflows/automerge.yml
- .github/workflows/ci.yml
- .github/workflows/codecoverage.yml
- .github/workflows/publish.yml
We want to allow sluggish jobs that are not hung some more time to finish.
> [TASK] Increase the CI timeouts

- .github/workflows/automerge.yml
We do not need the other trigger here.
> [TASK] Switch the automerge trigger to `pull_request`

- .github/workflows/ci.yml
- .github/workflows/codecoverage.yml
- .github/workflows/publish.yml
Those are more hassle than they are worth in this project.
> [TASK] Drop the timeouts from most CI jobs again

- .github/workflows/automerge.yml
> [TASK] Improve the automerge GH job comments

- CHANGELOG.md
- Documentation/Index.rst
- README.md
> [TASK] Mention the 12LTS crowdfunding campaign

- .github/workflows/ci.yml
- CHANGELOG.md
- composer.json
- ext_emconf.php
> [FEATURE] Add support for PHP 8.3

- CHANGELOG.md
- Classes/Domain/Model/CreationDateTrait.php
- Classes/Domain/Model/FrontendUser.php
- Classes/Domain/Model/FrontendUserGroup.php
- Classes/Domain/Model/ModificationDateTrait.php
- Configuration/Extbase/Persistence/Classes.php
- Configuration/TCA/Overrides/fe_groups.php
- Configuration/TCA/Overrides/fe_users.php
- Tests/Functional/Domain/Repository/Fixtures/UserGroupWithAllScalarData.xml
- Tests/Functional/Domain/Repository/Fixtures/UserWithAllScalarData.xml
- Tests/Functional/Domain/Repository/FrontendUserGroupRepositoryTest.php
- Tests/Functional/Domain/Repository/FrontendUserRepositoryTest.php
- Tests/Functional/Domain/Repository/FrontendUserWithCountryRepositoryTest.php
- Tests/Unit/Domain/Model/FrontendUserGroupTest.php
- Tests/Unit/Domain/Model/FrontendUserTest.php
- Tests/Unit/Domain/Model/FrontendUserWithCountryTest.php
> [FEATURE] Add `.creationDate` and `modificationDate` properties

- .github/workflows/ci.yml
- .github/workflows/codecoverage.yml
- CHANGELOG.md
- composer.json
- ext_emconf.php
> [TASK] Drop support for PHP 7.2/7.3

- .github/dependabot.yml
- composer.json
Also prevent further, incompatible updates by Dependabot.
> [TASK] Update the development dependencies

- .github/dependabot.yml
- Tests/Unit/Domain/Model/FrontendUserTest.php
- composer.json
- phive.xml
> [TASK] Upgrade to PHPUnit 9

- CHANGELOG.md
> [DOCS] Add a missing PR id to the changelog

- .gitattributes
- composer.json
- rector.php
> [FEATURE] Add Rector to our toolchain

- CHANGELOG.md
- Classes/Domain/Model/FrontendUser.php
- Classes/Domain/Model/FrontendUserGroup.php
- Tests/Functional/Domain/Repository/FrontendUserGroupRepositoryTest.php
- Tests/Functional/Domain/Repository/FrontendUserRepositoryTest.php
- Tests/Unit/Domain/Model/FrontendUserGroupTest.php
- Tests/Unit/Domain/Model/FrontendUserTest.php
- Tests/Unit/Domain/Repository/FrontendUserGroupRepositoryTest.php
- Tests/Unit/Domain/Repository/FrontendUserRepositoryTest.php
- rector.php
> [TASK] Use native type declarations for properties

- Classes/Domain/Model/FrontendUser.php
- Tests/Unit/Domain/Model/FrontendUserTest.php
> [CLEANUP] Make some type annotations more specific

- composer.json
> [FEATURE] Add dev support for Symfony 7

- CHANGELOG.md
- Configuration/TCA/Overrides/fe_groups.php
- Configuration/TCA/Overrides/fe_users.php
> [FEATURE] Add 12LTS-specific TCA

- Tests/Functional/Domain/Repository/FrontendUserGroupRepositoryTest.php
- Tests/Functional/Domain/Repository/FrontendUserRepositoryTest.php
> [CLEANUP] Use the Composer package name in the functional tests

- .github/workflows/ci.yml
- composer.json
> [BUGFIX] Re-enable the CI runs with lowest deps on PHP 8.2/8.3

- .github/workflows/ci.yml
> [TASK] Re-enable PHP 8.3 functional tests with lowest dependencies

- .github/workflows/ci.yml
> [FEATURE] Add Rector to CI

- .github/workflows/ci.yml
> [BUGFIX] Do not install PHIVE for the Rector CI job

- CHANGELOG.md
- Resources/Private/Language/de.locallang.xlf
- Resources/Private/Language/fr.locallang.xlf
- Resources/Private/Language/locallang.xlf
- Resources/Private/Language/nl.locallang.xlf
> [BUGFIX] Add `resname` to all language labels

- CHANGELOG.md
- Classes/Domain/Repository/DirectPersistInterface.php
- Classes/Domain/Repository/DirectPersistTrait.php
Also mark some classes as `@internal`.
Fixes #476
> [CLEANUP] Improve the annotations

- .gitattributes
- .github/workflows/ci.yml
- Build/bin/console
- composer.json
The corresponding GitHub Action has been discontinued.
> [BUGFIX] Switch the XLIFF linting to Symfony tools

- rector.php
> [TASK] Add more Rector rules from Rector 2.3.0

- CHANGELOG.md
- Configuration/TCA/Overrides/fe_groups.php
- Configuration/TCA/Overrides/fe_users.php
- Resources/Private/Language/locallang.xlf
> [TASK] Add labels for `crdate` and `tstamp`

- Resources/Private/Language/locallang.xlf
Approving only applies to translations, not to the original English labels.
Fixes #570
> [TASK] Drop `approved="yes"` from the English locallang files

- rector.php
> [TASK] Modernize the Rector configuration

- CHANGELOG.md
- ext_tables.sql
> [BUGFIX] Set the default gender to "none" in the SQL table definition

- .github/dependabot.yml
- composer.json
> [BUGFIX] Allow updates to `composer-normalize` again

- composer.json
> [BUGFIX] Use only busybox compatible `find` options

- phpstan.neon
> [TASK] Configure PHPStan to be even more strict

- .github/workflows/automerge.yml
- .github/workflows/ci.yml
- .github/workflows/codecoverage.yml
- .github/workflows/publish.yml
> [TASK] Switch the Ubuntu CI runners to 24.04

- CHANGELOG.md
- Classes/Domain/Model/CreationDateTrait.php
- Classes/Domain/Model/ModificationDateTrait.php
- Classes/Domain/Repository/DirectPersistTrait.php
- phpstan-baseline.neon
> [BUGFIX] Use the proper annotations for traits

- composer.json
We are not using it.
Fixes #685
> [TASK] Drop `bnf/phpstan-psr-container` as a dev dependency

- .github/workflows/ci.yml
Also sort the entries consistently.
> [TASK] Add missing CI matrix entry

- CHANGELOG.md
- Classes/Domain/Model/FrontendUser.php
- Tests/Unit/Domain/Model/FrontendUserTest.php
> [FEATURE] Add `FrontendUser::getValidEmail()`

- .github/workflows/ci.yml
> [FEATURE] Add a CI job to check the documentation rendering

- CHANGELOG.md
- Classes/Domain/Model/FrontendUser.php
- Tests/Unit/Domain/Model/FrontendUserTest.php
> [FEATURE] Add `Frontenduser.getDisplayName()`

- README.md
> [DOCS] Remove the download counter badge from the README

- .github/workflows/ci.yml
- .github/workflows/codecoverage.yml
- .github/workflows/publish.yml
In this case, we don't need to quote the strings.
https://stackoverflow.com/questions/19109912/yaml-do-i-need-quotes-for-strings-in-yaml
> [CLEANUP] Do not quote workflow/job names for GitHub actions
