- composer.json
In those directories, duplicate code is to be expected, and it is
perfectly fine there.
> [BUGFIX] Do not check `Configuration` and `Tests` for duplicate code

- Classes/Domain/Model/FrontendUser.php
- Classes/Domain/Model/FrontendUserGroup.php
- Tests/Functional/Domain/Repository/FrontendUserGroupRepositoryTest.php
- Tests/Functional/Domain/Repository/FrontendUserRepositoryTest.php
If an entity is read from the DB, the constructor is not called. So we
need to use `initializeObject` to initialize the associations properly.
> [BUGFIX] Initialize all associations even without the constructor

- .github/workflows/ci.yml
This fixes a breakage with TYPO3 V9.
> [BUGFIX] Use Composer 2.2 for the unit and functional tests an CI

- composer.json
This allows Composer installation with PHPUnit 7 again.
> [BUGFIX] Allow more versions of PHPCov

- CHANGELOG.md
- Classes/Domain/Model/FrontendUser.php
- Classes/Domain/Model/FrontendUserGroup.php
This also reduces code duplication.
> [CLEANUP] Reuse `initializeObject` from the constructor

- .github/workflows/codecoverage.yml
Now the Composer caches between the coverage generation and the test
runs are shared. Copying changes from one CI workflow to the other
now is easier as well.
> [TASK] Align the installation instructions on CI

- composer.json
PHPUnit has dropped its dependency on Prophecy. In order to keep using
Prophecy in our tests, we need to add it as an explicit (development)
dependency.
Also, relying on transitive dependencies is bad practice anyway.
> [BUGFIX] Explicitly require Prophecy

- .gitignore
As this directory was introduced (and git-ignored) in the current development
branch, ignoring it in all active branches makes switching between branches
less of a hassle.
> [BUGFIX] Git-ignore the `tools/` directory

- CHANGELOG.md
- Classes/Domain/Model/FrontendUser.php
- Classes/Domain/Model/FrontendUserGroup.php
- Tests/Functional/Domain/Repository/Fixtures/UserGroupWithAllScalarData.xml
- Tests/Functional/Domain/Repository/Fixtures/UserWithAllScalarData.xml
- Tests/Functional/Domain/Repository/FrontendUserGroupRepositoryTest.php
- Tests/Functional/Domain/Repository/FrontendUserRepositoryTest.php
- Tests/Functional/Domain/Repository/FrontendUserWithCountryRepositoryTest.php
- Tests/Unit/Domain/Model/FrontendUserGroupTest.php
- Tests/Unit/Domain/Model/FrontendUserTest.php
This property was be removed in TYPO3 11LTS.
Fixes #121
> [TASK] Drop the `lockToDomain` property

- .github/workflows/ci.yml
- .github/workflows/codecoverage.yml
This unblocks using the development version of TYPO3.
Fixes #172
> [TASK] Require `typo3/cms-core` instead of `typo3/minimal` on CI

- composer.json
As it is not possible to install system extensions in different versions (e.g., extbase 10.4.7 together with fluid 10.4.11), we should require the same versions for all system extensions for consistency.
> [TASK] Make the required system extension versions consistent

- .github/workflows/ci.yml
We need some bug fixes in newer versions of the dependencies to have the PHP 8.2 build warning-free.
> [TASK] Do not run the PHP 8.2 tests with the lowest dependencies (#1210)

- .github/dependabot.yml
Dependabot cannot handle multi-version dependencies.
Fixes #203
> [TASK] Exclude `symfony/routing` from Dependabot

- .github/dependabot.yml
Dependabot will happily mangle them (like e.g., in #210).
> [BUGFIX] Block Dependabot updates for multi-version dependencies

- CHANGELOG.md
- Configuration/Extbase/Persistence/Classes.php
This field was removed some time ago, but I forgot to also remove the mapping configuration for it.
> [TASK] Drop the property mapping for the removed `lockToDomain` property

- composer.json
We are not using Prophecy anymore and hence do not need PHPStan to have additional configuration for this.
Fixes #271
> [TASK] Drop the `jangregor/phpstan-prophecy` Composer dependency

- composer.json
- ext_emconf.php
… for the Extbase models deprecated in TYPO3 11LTS and removed in 12LTS.
Fixes #354
> [TASK] Mention in the title that this is a drop-in replacement

- CHANGELOG.md
- Classes/Domain/Model/FrontendUser.php
- Tests/Functional/Domain/Repository/Fixtures/UserWithAllScalarData.xml
- Tests/Functional/Domain/Repository/FrontendUserRepositoryTest.php
- Tests/Functional/Domain/Repository/FrontendUserWithCountryRepositoryTest.php
- Tests/Unit/Domain/Model/FrontendUserTest.php
> [TASK] Drop the `fax` field

- .github/dependabot.yml
- composer.json
Now that we've dropped support for PHP 7.2/7.3 and TYPO3 10LTS, we can have higher versions of some development dependencies.
> [TASK] Allow higher versions of the dev dependencies

- composer.json
Now that we don't have the corresponding country field anymore, there is no point suggestion the static_info_tables extension anymore.
> [TASK] Drop the suggestion for static_info_tables

- .github/dependabot.yml
We are not using that package anymore.
> [TASK] Drop sjbr/static-info-tables from the Dependabot configuration

- .github/workflows/ci.yml
- composer.json
- phive.xml
For this project, copy paste detection does not provide any benefit.
Also, removing this CI job speeds up the CI builds a bit.
> [TASK] Drop PHP copy paste detection

- .github/workflows/ci.yml
- composer.json
This is overkill for only the `composer.json`, which already get checked with `composer install` and `composer normalize`.
Removing this job speeds up the CI builds and helps save resources.
> [TASK] Drop the JSON linting from the CI jobs

- README.md
- actually use the V12 badge for V12
- fix the license badge
- reorder the version badges to be in ascending order
Fixes #546
Fixes #547
> [BUGFIX] Fix the badges in the README

- Tests/Functional/Domain/Repository/FrontendUserGroupRepositoryTest.php
- Tests/Unit/Domain/Model/FrontendUserGroupTest.php
- Tests/Unit/Domain/Model/FrontendUserTest.php
- Tests/Unit/Domain/Repository/FrontendUserGroupRepositoryTest.php
- Tests/Unit/Domain/Repository/FrontendUserRepositoryTest.php
Also harden some array accesses in the tests.
Fixes #586
> [CLEANUP] Use specific PHPStan error code in the annotations

- CHANGELOG.md
- Classes/Domain/Model/FrontendUser.php
- Classes/Domain/Model/Gender.php
- Configuration/TCA/Overrides/fe_users.php
- Tests/Functional/Domain/Repository/FrontendUserRepositoryTest.php
- Tests/Unit/Domain/Model/GenderTest.php
For TYPO3 V13, the gender values will change. So we need to be able to make these values TYPO3-version-specific later.
Also deprecate the gender constants.
Fixes #588
> [FEATURE] Add a wrapper class for gender values

- composer.json
Instead, we'll run the functional tests on PHP 8.4 only with the highest dependencies.
> [TASK] Remove Symfony DI as a dev dependency again

- .php-cs-fixer.php
@see https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/8337
> [BUGFIX] Make PHP-CS-Fixer >= 3.66 compatible with PHPUnit 9.x

- Configuration/TCA/Overrides/fe_users.php
> [CLEANUP] Use only booleans for `exclude` in TCA
